version: '3.3'

networks:
  network:

volumes:
  spring-batch-mysql:

services:
  mysql:
    image: "mysql:8.0"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    container_name: beside-mysql
    networks:
      - network
    ports:
      - "33060:3306"
    environment:
      - MYSQL_DATABASE=spring-batch
      - MYSQL_USER=spring-batch
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - spring-batch-mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d