logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:33060/spring-batch?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    max-lifetime: 300000
    connection-timeout: 3000
    username: root
    password: password
  batch:
    jdbc:
      initialize-schema: always